language: node_js
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - '10'
jobs:
  include:
    - stage: validate
      script: jupiter-scripts lint
    - script: yarn run ci
    - stage: deploy
      script: yarn run build
      after_success: jupiter-scripts deploy
stages:
  validate
  deploy
