version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  - cypress/validate:
      run: yarn install
      run: yarn run validate

  - cypress/deploy:
      run: yarn install
      run: yarn run build
      run: yarn run deploy

workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - validate
      - deploy:
          context: package
          requires:
            - validate
