version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: yarn run deploy

workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        context: package